### PR TITLE
Create valid library type, rather than component.

### PR DESCRIPTION
**Pull request by notlee**
Remove the primary mixin and demos. These should not be expected of a library.

### CODE REVIEW

**Comment by notlee** [comment]
I'll tag this as v2.2.19 on this branch if everything looks good, then close the PR.

**Comment by notlee** [comment]
The test command will fail. This test component is here to test an obt fix.

**Review by JakeChampion — APPROVED** [review]

**Comment by notlee** [comment]
Ugh, I didn't actually update the type in origami.json! And didn't notice as my local obt branch had a bug, which this was made to test

**Comment by notlee** [comment]
I've made a release to fix the previous issue, and another to add a library test with default CSS output on import.

**Pull request closed without merging**
