### PR TITLE
Set origamiVersion to "2.0"

### PR DESCRIPTION
**Pull request by chee**

### CODE REVIEW

**Comment by JakeChampion** [comment]
I think we need to merge and release the repo-data work before we could merge this change in, that way repo-data can store the version correctly -- https://github.com/Financial-Times/origami-repo-data/pull/308

**Comment by chee** [comment]
> I think we need to merge and release the repo-data work before we could merge this change in, that way repo-data can store the version correctly -- [Financial-Times/origami-repo-data#308](https://github.com/Financial-Times/origami-repo-data/pull/308)

yep

**Comment by chee** [comment]
> I think we need to merge and release the repo-data work before we could merge this change in, that way repo-data can store the version correctly -- [Financial-Times/origami-repo-data#308](https://github.com/Financial-Times/origami-repo-data/pull/308)

repo data will already store the version correctly, though, i didn't make any changes to how it stores the version. repo data was already using strings.

**Comment by chee** [comment]
I will update the README table in the final (2.1.16) release

**Comment by chee** [comment]
i'm going to release this one as 2.1.0-beta.1, then release it again as 2.1.0, then i will release the rest in order as patches

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v2.1.0-beta.0 :tada:

**Pull request merged**
