### PR TITLE
stop using origami-ci-tools to publish to npm

### PR DESCRIPTION
**Pull request by JakeChampion**
Based on discussion here -- https://github.com/Financial-Times/origami-ci-tools/pull/95#issuecomment-780694654

### CODE REVIEW

**Comment by notlee** [comment]
Nice! Shall we also add a test workflow as part of this to make sure we can remove ci-tools from other components ok?
https://github.com/Financial-Times/o-table/blob/31babc628bb7ca9e5d74427647a7ca3a2c0c9548/.github/workflows/test-origami-component.yml#L17

**Comment by JakeChampion** [comment]
> Nice! Shall we also add a test workflow as part of this to make sure we can remove ci-tools from other components ok?
> [Financial-Times/o-table@`31babc6`/.github/workflows/test-origami-component.yml#L17](https://github.com/Financial-Times/o-table/blob/31babc628bb7ca9e5d74427647a7ca3a2c0c9548/.github/workflows/test-origami-component.yml#L17)

Will do 👍

**Comment by notlee** [comment]
Looks like there's a line in there we'll be able to remove no bundle size cli is no more for branches:
https://github.com/Financial-Times/o-table/blob/31babc628bb7ca9e5d74427647a7ca3a2c0c9548/.github/workflows/test-origami-component.yml#L9

**Comment by JakeChampion** [comment]
the new test workflow will fail due to a bug we have when the beta obt is globally installed

**Review by notlee — APPROVED** [review]
>the new test workflow will fail due to a bug we have when the beta obt is globally installed

[sorted](https://github.com/Financial-Times/origami-build-tools/pull/975)

**Pull request merged**
